name: integration-tests
on:
  workflow_dispatch:
  schedule:
    - cron: 30 14 * * 0-5

jobs:
  integration-branch-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Generated Branch
        uses: dawidd6/action-delete-branch@v2.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: gh-pages
